version: "3.9"
services: 
  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data